language: node_js
node_js:
  - "12"
  - "10"
  - "8"
before_install:
  - "npm install -g meteorite"
  - "curl https://install.meteor.com | /bin/sh"
script: "./.unittest/test-packages/test-all-in-console.js"
